services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: registroescolar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/registroescolar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
