services:
  - type: web
    name: backend-escolar
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: ${SPRING_DATASOURCE_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${SPRING_DATASOURCE_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${SPRING_DATASOURCE_PASSWORD}
