services:
  - type: web
    name: backend-escolar
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d0m5q3juibsr7385lmsg-a.oregon-postgres.render.com:5432/registroscolar_db?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: registroscolar_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 1PbLmTCfd0A0niLugDTH0vtquop1Bwri
